const SRC = {
  hawkerRoots: 'https://www.roots.gov.sg/ich-landing/ich/hawker-culture',
  hawkerUnesco: 'https://ich.unesco.org/en/RL/hawker-culture-in-singapore-community-dining-and-culinary-practices-in-a-multicultural-urban-context-01568',
  food: 'https://www.visitsingapore.com/things-to-do/dining/local-food-and-drinks/',
  cuisine: 'https://www.roots.gov.sg/stories-landing/stories/Serving-Up-a-Legacy',
  singlish: 'https://www.nlb.gov.sg/main/article-detail?cmsuuid=5d5de338-98c5-4a97-9b51-727e807d6507',
  singlishWords: 'https://www.languagecouncils.sg/goodenglish/resources/singlish-words',
  symbols: 'https://www.nhb.gov.sg/what-we-do/our-work/community-engagement/education/resources/national-symbols',
  identity: 'https://www.mccy.gov.sg/sectors/resilience-and-engagement/national-identity-and-symbols/',
  historyTimeline: 'https://sg75.pa.gov.sg/the-singapore-story/',
  yusof: 'https://www.istana.gov.sg/the-president/former-presidents/encik-yusof-ishak/',
  hdb: 'https://www.hdb.gov.sg/about-us/our-role/public-housing-a-singapore-icon',
  mrt: 'https://www.lta.gov.sg/content/ltagov/en/getting_around/public_transport/rail_network.html',
  orchard: 'https://www.roots.gov.sg/places/places-landing/Places/landmarks/orchard-heritage-trail/orchard-road',
  ubin: 'https://www.nparks.gov.sg/visit/parks/pulau-ubin',
  macritchie: 'https://www.nparks.gov.sg/visit/parks/central-catchment-nature-reserve/activities/treetop-walk',
  esplanade: 'https://www.esplanade.com/visit-esplanade/architecture-and-building',
  traffic: 'https://www.police.gov.sg/Advisories/Traffic/Traffic-Matters',
  currency: 'https://www.nlb.gov.sg/main/article-detail?cmsuuid=ac36a2e4-5620-4812-9405-e5bd24023213',
  chinHan: 'https://www.imdb.com/name/nm1977856/',
  fannWong: 'https://www.imdb.com/name/nm0939056/',
  pierrePng: 'https://www.imdb.com/name/nm0687771/',
  rossButler: 'https://www.imdb.com/name/nm5224900/',
  iloIlo: 'https://www.quinzaine-cineastes.fr/en/film/ilo-ilo',
  shirkers: 'https://www.sundance.org/blogs/2018-sundance-film-festival-awards-announced-3/',
  popAye: 'https://www.kirstentan.com/portfolio/popaye',
  ericKhoo: 'https://www.festival-cannes.com/en/p/eric-khoo/',
  booJunfeng: 'https://www.imda.gov.sg/about-imda/research-and-statistics/support-for-industry-sectors/media/film/production-companies/peanut-pictures',
  sonnyLiew: 'https://artofcharliechan.com/',
  nationalSongs: 'https://www.nlb.gov.sg/main/article-detail?cmsuuid=07d7e2c6-e52c-4be5-9d0b-eb9080448908',
  phuaChuKang: 'https://biblioasia.nlb.gov.sg/all-sections/vol-20-issue-3-oct-dec-2024-colour-tv-history-singapore/',
  stefanieSun: 'https://www.nlb.gov.sg/main/article-detail?cmsuuid=420413ab-c672-4ca1-8aeb-c99362c99bae',
  taufik: 'https://www.nlb.gov.sg/main/article-detail?cmsuuid=ab4d6637-769e-4406-9250-3b9a161d0c34',
  tanya: 'https://www.nlb.gov.sg/main/article-detail?cmsuuid=ca25fc08-e3fb-4691-af11-214a12173c67',
  shabir: 'https://tv.apple.com/us/person/shabir/umc.cpc.23dh9e6urx06bpqo63f00jtuy',
  amanda: 'https://www.ethosbooks.com.sg/products/ministry-of-moral-panic',
  haresh: 'https://b1965.sg/',
  ivan: 'https://www.nlb.gov.sg/main/article-detail?cmsuuid=e17c8e1f-41dc-4d44-927d-b7cff1053bbd',
  jjLin: 'https://music.apple.com/sg/artist/jj-lin/216635866',
  schooling: 'https://www.olympics.com/ioc/news/joseph-schooling-makes-waves-in-the-pool-to-win-singapore-s-first-olympic-gold',
  tanHoweLiang: 'https://www.olympics.com/en/news/weightlifter-tan-beats-pain-barrier-for-singapore-s-first-medal',
  maxMaeder: 'https://www.olympics.com/en/news/paris-2024-sailing-austria-valentin-bontus-takes-mens-kite-gold',
  yipPinXiu: 'https://www.paralympic.org/pin-xiu-yip',
  shantiPereira: 'https://worldathletics.org/athletes/singapore/veronica-shanti-pereira-14472153',
  lohKeanYew: 'https://bwfworldchampionships.bwfbadminton.com/news-single/2021/12/20/loh-kean-yew-world-champion',
  tableTennisOlympics: 'https://www.nlb.gov.sg/main/article-detail?cmsuuid=85354baa-3766-4f88-a1a8-7082357a62a8',
  laurentiaTan: 'https://www.paralympic.org/feature/laurentia-tan-i-may-not-be-able-dance-horse-we-can-do-ballet-together',
  nurSyahidah: 'https://www.worldarchery.sport/news/169129/nur-syahidah-alim-wins-singapores-first-ever-archery-world-champion-title',
  fandiAhmad: 'https://www.nlb.gov.sg/main/article-detail?cmsuuid=ccd93711-15d1-4005-8451-3ac5ed6b7ae9',
  angPengSiong: 'https://www.nlb.gov.sg/main/article-detail?cmsuuid=14fe3ea2-edfb-4242-a8c8-96d82c953664',
  remyOng: 'https://www.roots.gov.sg/collection-landing/listing/1594794',
  sheikFarhan: 'https://www.mccy.gov.sg/get-involved/sports/sheik-farhan/',
  lauYwen: 'https://fie.org/news/336-lau-ywen-wins-singapore-s-first-ever-gold-medal-at-cadet-and-junior-world-championships',
  waterPolo: 'https://www.worldaquatics.com/news/1908053/challengers-cup-water-polo-set-for-singapore-debut',
  youthOlympics: 'https://www.olympics.com/en/olympic-games/singapore-2010',
  worldAquatics: 'https://www.worldaquatics.com/news/4271547/singapore-2025-50-days-southeast-asia-first-world-aquatics-championships',
  kallang: 'https://www.sportshub.com.sg/who-we-are/awards-recognition',
  nationalStadium: 'https://www.sportshub.com.sg/venues-facilities/national-stadium',
  soundBlaster: 'https://www.nlb.gov.sg/main/article-detail?cmsuuid=696e7ff5-1e19-46d6-8f50-051d17a3e9d4',
  thumbDrive: 'https://www.nlb.gov.sg/main/article-detail?cmsuuid=6e32df59-972b-4ef0-8c5f-28ee2d1d24bf',
  newater: 'https://www.pub.gov.sg/Public/WaterLoop/OurWaterStory/NEWater',
  erp: 'https://onemotoring.lta.gov.sg/content/onemotoring/home/driving/ERP/ERP.html',
  sling: 'https://www.raffles.com/magazine/singapore/How-the-Singapore-Sling-conquered-the-world-/',
  nightSafari: 'https://www.mandai.com/en/night-safari.html',
  f1: 'https://www.formula1.com/en/racing/2026/singapore',
  butterfly: 'https://www.changiairport.com/en/experience/attractions-directory/butterfly-garden.html',
  skyGreens: 'https://www.edb.gov.sg/content/dam/edb-en/business-insights/insights/how-companies-like-south-pole-and-edb-renewables-are-tapping-singapores-green-economy-to-develop-sustainable-solutions/how-companies-like-south-pole-and-edb-renewables-are-tapping-singapores-green-economy-to-develop-sustainable-solutions-qr.pdf',
  rainVortex: 'https://www.jewelchangiairport.com/en/attractions/rain-vortex.html',
  australiaBrief: 'https://www.dfat.gov.au/geo/singapore/singapore-country-brief',
  australiaCsp: 'https://www.dfat.gov.au/geo/singapore/Pages/joint-declaration-on-a-csp',
  wallaby: 'https://www.mindef.gov.sg/news-and-events/latest-releases/2010nov19-news-releases-02417/',
  fpda: 'https://www.fivepowerdefencearrangements.org/',
  digitalAgreement: 'https://www.mti.gov.sg/trade-international-economic-relations/agreements/digital-economy-agreements-dea/sadea/',
  greenAgreement: 'https://www.dfat.gov.au/geo/singapore/singapore-australia-green-economy-agreement',
  canberra: 'https://www.canberratimes.com.au/story/6139236/singapore-calls-new-mrt-station-canberra/',
  christmasIsland: 'https://www.nlb.gov.sg/main/article-detail?cmsuuid=33f573ac-f510-4d09-9bad-1cdeff6292aa',
  changiPow: 'https://www.awm.gov.au/collection/C2695038'
};

export const performanceCategories = [
  { id: 'food', label: 'Food & hawker culture' },
  { id: 'language', label: 'Language & Singlish' },
  { id: 'history', label: 'History & heritage' },
  { id: 'sport', label: 'Sport' },
  { id: 'screen-stage', label: 'Film, TV & theatre' },
  { id: 'arts', label: 'Music, books & art' },
  { id: 'innovation', label: 'Innovation & design' },
  { id: 'australia', label: 'Singapore–Australia' }
];

const CATEGORY = {
  FOOD: 'food',
  LANGUAGE: 'language',
  HISTORY: 'history',
  SPORT: 'sport',
  SCREEN_STAGE: 'screen-stage',
  ARTS: 'arts',
  INNOVATION: 'innovation',
  AUSTRALIA: 'australia'
};

const q = (topic, question, options, answer, explain, source, category = null) => ({ topic, q: question, options, answer, explain, source, category });

export const rounds = [
  {
    title: 'Hawker food files',
    description: 'One food round only: hawker basics, dish clues and ingredient mysteries—with no second serving of the same topic.',
    category: CATEGORY.FOOD,
    questions: [
      q('hawker-unesco-year', 'Singapore’s hawker culture joined UNESCO’s intangible heritage list in which year?', ['2015', '2018', '2020', '2023'], 2, 'UNESCO inscribed Hawker Culture in Singapore in 2020. A very official reason to say “makan”.', SRC.hawkerUnesco, CATEGORY.HISTORY),
      q('hawker-resettlement', 'Why were many purpose-built hawker centres created from the 1970s?', ['To resettle street hawkers', 'To replace hotels', 'To host cooking contests', 'To serve only tourists'], 0, 'The centres helped resettle itinerant street hawkers while improving sanitation and infrastructure.', SRC.hawkerRoots, CATEGORY.HISTORY),
      q('hawker-centre-format', 'A hawker centre is best described as…', ['One giant restaurant', 'A supermarket tasting room', 'A hotel buffet', 'Independent food stalls with shared seating'], 3, 'Many independent cooked-food and drink stalls share one public dining space. One table, twenty temptations.', SRC.hawkerRoots, CATEGORY.HISTORY),
      q('kopi-o-kosong', 'What does “kopi O kosong” order?', ['Coffee with evaporated milk', 'Black coffee without sugar', 'Iced coffee with milk', 'Tea without sugar'], 1, 'O removes milk; kosong removes sugar. Beverage algebra, Singapore edition.', SRC.food),
      q('teh-tarik', 'What makes teh tarik “tarik”?', ['It is pulled between vessels', 'It contains lime', 'It is frozen', 'It comes with a straw'], 0, 'Tarik means pulled: the tea is poured repeatedly between vessels to cool and aerate it.', SRC.food),
      q('chicken-rice', 'What makes the rice in Hainanese chicken rice so fragrant?', ['Coconut cream only', 'Tomato stock', 'Chicken stock, fat and aromatics', 'Rose syrup'], 2, 'The rice is cooked with chicken stock, fat and aromatics. It is absolutely not a side character.', SRC.cuisine),
      q('satay', 'Which clue identifies satay?', ['Rice cakes with radish', 'Skewered grilled meat with peanut sauce', 'Fish in coconut broth', 'Soybean pudding'], 1, 'Satay is seasoned meat grilled on skewers and commonly served with peanut sauce.', SRC.cuisine),
      q('kaya-toast', 'What is spread inside classic kaya toast?', ['Prawn paste and chilli', 'Peanut butter only', 'Mashed durian', 'Coconut-and-egg jam with butter'], 3, 'Kaya is a sweet coconut-and-egg jam, usually scented with pandan and paired with butter.', SRC.food),
      q('laksa', 'Rice noodles in a spicy coconut-based broth point to which dish?', ['Laksa', 'Bak kut teh', 'Mee rebus', 'Chwee kueh'], 0, 'Singapore’s Katong-style laksa is rich, spicy and coconut-based. White shirts enter at their own risk.', SRC.food),
      q('char-kway-teow', 'Which noodle defines char kway teow?', ['Glass noodles', 'Yellow wheat noodles', 'Flat rice noodles', 'Buckwheat soba'], 2, 'Kway teow are flat rice noodles, stir-fried over high heat for that prized wok hei.', SRC.food),
      q('nasi-lemak', 'What gives nasi lemak rice its signature richness?', ['Chicken stock', 'Coconut milk', 'Cheese', 'Sesame paste'], 1, 'Nasi lemak rice is traditionally cooked with coconut milk and often pandan.', SRC.food),
      q('carrot-cake', 'What is the “carrot” in Singaporean carrot cake?', ['Orange carrot', 'Pumpkin', 'Sweet potato', 'White radish'], 3, 'It is a savoury radish-cake dish fried with egg—not a dessert having an identity crisis.', SRC.food),
      q('otak-otak', 'Otak-otak is usually made from…', ['Spiced fish paste', 'Sweet bean paste', 'Mashed potato', 'Coffee grounds'], 0, 'Otak-otak is seasoned fish paste commonly grilled inside leaf wrapping.', SRC.food),
      q('chilli-crab', 'Which sauce belongs to Singapore chilli crab?', ['Plain butter', 'Black coffee reduction', 'Sweet-savoury tomato-chilli sauce', 'Cold mayonnaise'], 2, 'Its glossy tomato-chilli sauce is sweet, savoury and spicy. Mantou handles the clean-up operation.', SRC.food),
      q('mee-rebus', 'Mee rebus is yellow noodles served in what kind of gravy?', ['Clear chicken broth', 'Thick sweet-spicy gravy', 'Cold sesame dressing', 'Coconut dessert soup'], 1, 'Mee rebus comes with a rich, sweet-spicy gravy often thickened with potato.', SRC.food),
      q('chendol', 'Which trio is central to chendol?', ['Coffee, cocoa and cream', 'Mango, yoghurt and oats', 'Soy milk, ginger and egg', 'Green jelly, coconut milk and palm sugar'], 3, 'Pandan-green jelly, coconut milk and gula melaka form chendol’s greatest-hits lineup.', SRC.food),
      q('fish-head-curry', 'Which Singapore dish combines South Indian curry with a fish part prized by Chinese diners?', ['Fish head curry', 'Murtabak', 'Mee siam', 'Otak-otak'], 0, 'Fish head curry developed in Singapore through a distinctly cross-cultural restaurant context.', SRC.cuisine),
      q('hokkien-mee', 'What gives Singapore Hokkien mee much of its savoury depth?', ['Cheese sauce', 'Prawn-and-pork stock', 'Rose water', 'Coconut jam'], 1, 'The noodles are fried with a seafood-rich prawn-and-pork stock, then served with lime and sambal.', SRC.food),
      q('chwee-kueh', 'Steamed rice cakes topped with savoury preserved radish are called…', ['Putu piring', 'Ang ku kueh', 'Chwee kueh', 'Muah chee'], 2, 'Chwee kueh pairs soft rice cakes with chai poh, a savoury preserved-radish topping.', SRC.food),
      q('sup-tulang', 'Which dish is famous for mutton bones and vivid red gravy?', ['Bak kut teh', 'Soto ayam', 'Mutton briyani', 'Sup tulang merah'], 3, 'Sup tulang merah is a hands-on bone-marrow dish. Napkins: compulsory. White sleeves: courageous.', SRC.cuisine)
    ]
  },
  {
    title: 'Singlish, can?',
    description: 'Twenty different expressions. Translate the mood, not just the words, and don’t anyhow answer.',
    category: CATEGORY.LANGUAGE,
    questions: [
      q('singlish-definition', 'Singlish is best described as…', ['A spelling reform', 'English spoken only by tourists', 'Informal colloquial Singapore English', 'Singapore’s national language'], 2, 'Singlish is a systematic colloquial variety shaped by Singapore’s multilingual environment.', SRC.singlish),
      q('singlish-lah', 'What does “lah” usually add to a sentence?', ['Past tense', 'A person’s name', 'The meaning “lunch”', 'Emphasis or social tone'], 3, 'Lah is a discourse particle whose effect depends on tone and context. Tiny word, big workload.', SRC.singlish),
      q('singlish-shiok', 'A meal described as “shiok” was probably…', ['Very satisfying', 'Legally required', 'Slightly wet', 'Free of charge'], 0, 'Shiok expresses strong pleasure or satisfaction, especially after good food.', SRC.singlishWords),
      q('singlish-blur', 'If someone is “blur”, they are…', ['Dressed in blue', 'Confused or unaware', 'Extremely athletic', 'Speaking formally'], 1, 'Blur describes someone confused, slow to catch on or not fully aware of what is happening.', SRC.singlishWords),
      q('singlish-kiasu', '“Kiasu” describes a fear of…', ['Rain', 'Public speaking', 'Spicy food', 'Losing out'], 3, 'Kiasu comes from Hokkien and refers to fear of losing out. Queue position suddenly becomes strategy.', SRC.singlishWords),
      q('singlish-paiseh', '“Paiseh” is closest to…', ['Embarrassed or sorry', 'Very hungry', 'Please hurry', 'Well done'], 0, 'Paiseh can convey embarrassment, awkwardness or apology, depending on context.', SRC.singlishWords),
      q('singlish-alamak', '“Alamak!” is closest to which reaction?', ['Good morning!', 'Oh no!', 'Please sit.', 'That is delicious.'], 1, 'Alamak expresses surprise, dismay or exasperation. Especially useful when the clock says 01.', SRC.singlishWords),
      q('singlish-atas', 'An “atas” café is probably…', ['Remote', 'Closed', 'Fancy or high-class', 'Very noisy'], 2, 'Atas literally means upstairs in Malay and colloquially suggests posh or upmarket.', SRC.singlishWords),
      q('singlish-makan', 'If a colleague asks “Makan?”, what are they suggesting?', ['Eat', 'Sleep', 'Leave work', 'Catch a train'], 0, 'Makan means eat or food and is widely used in everyday Singaporean speech.', SRC.singlish),
      q('singlish-jialat', '“Jialat” signals that a situation is…', ['Perfectly organised', 'Bad or troublesome', 'Almost free', 'Very quiet'], 1, 'Jialat means something is serious, awful or in trouble. Jialat—the projector cable is missing.', SRC.singlishWords),
      q('singlish-ulu', 'An “ulu” location is…', ['Beside the CBD', 'Luxurious', 'Underground', 'Remote or out of the way'], 3, 'Ulu describes somewhere remote or inconveniently far.', SRC.singlishWords),
      q('singlish-bo-jio', '“Bo jio!” complains that someone…', ['Did not invite you', 'Ordered too much chilli', 'Paid too early', 'Spoke too softly'], 0, 'Bo jio means “never invite”. Standard reply to colleagues posting lunch photos without you.', SRC.singlishWords),
      q('singlish-sabo', 'To “sabo” a colleague is to…', ['Buy them lunch', 'Praise their work', 'Sabotage or put them on the spot', 'Reserve their seat'], 2, 'Sabo is short for sabotage and can mean pranking someone or landing them in difficulty.', SRC.singlishWords),
      q('singlish-arrow', 'If you “arrow” someone, you…', ['Give directions', 'Assign them a task', 'Cancel their leave', 'Order their coffee'], 1, 'To arrow someone is to nominate or assign them a job—often with breathtaking speed.', SRC.singlishWords),
      q('singlish-own-time', '“Own time, own target” means…', ['Finish immediately', 'Work only at night', 'Proceed independently at your own pace', 'Copy the next team'], 2, 'The phrase signals independent action at one’s own pace and has roots in local military usage.', SRC.singlish),
      q('singlish-talk-cock', 'To “talk cock” is to…', ['Discuss poultry science', 'Whisper formally', 'Deliver a lecture', 'Talk nonsense or banter'], 3, 'It means to talk nonsense or chat idly. No chickens need attend the meeting.', SRC.singlishWords),
      q('singlish-sian', '“Sian” usually expresses…', ['Boredom or weary frustration', 'Great excitement', 'Formal approval', 'Extreme hunger'], 0, 'Sian captures boredom, tired resignation or frustration in one efficient syllable.', SRC.singlishWords),
      q('singlish-wait-long-long', 'Someone says “wait long long”. Should you expect it soon?', ['Yes, immediately', 'No, probably not', 'Exactly twenty minutes', 'Only after lunch'], 1, 'The phrase sarcastically suggests the hoped-for event is unlikely to happen.', SRC.singlish),
      q('singlish-chope', 'What does it mean to “chope” a seat?', ['Clean it', 'Share it', 'Reserve it', 'Remove it'], 2, 'To chope is to reserve a place—often using a tissue packet with astonishing authority.', SRC.singlishWords),
      q('singlish-dabao', 'What does “da bao” or “dabao” mean at a food stall?', ['Add chilli', 'Eat slowly', 'Split the bill', 'Pack it for takeaway'], 3, 'Da bao means to pack food to take away. Stomach says cannot; takeaway container says can.', SRC.singlish)
    ]
  },
  {
    title: 'Singapore sporting legends',
    description: 'Athletes, unlikely world firsts and the Kallang Roar—twenty ways the Little Red Dot plays big.',
    category: CATEGORY.SPORT,
    questions: [
      q('schooling-olympic-gold', 'Joseph Schooling won Singapore’s first Olympic gold in which event?', ['200m freestyle', '50m breaststroke', '100m butterfly', '400m medley'], 2, 'Schooling won the 100m butterfly at Rio 2016. For 50.39 seconds, Singapore collectively forgot to breathe.', SRC.schooling),
      q('tan-howe-liang-first-medal', 'Singapore’s first Olympic medal came from Tan Howe Liang in which sport?', ['Weightlifting', 'Boxing', 'Badminton', 'Diving'], 0, 'Tan lifted through pain to win silver at Rome 1960—the nation’s first Olympic medal.', SRC.tanHoweLiang),
      q('max-maeder-formula-kite', 'Max Maeder’s historic Paris 2024 bronze came in which sailing event?', ['Laser', 'Windsurfing', '470 dinghy', 'Formula Kite'], 3, 'At 17, Maeder won Formula Kite bronze and became Singapore’s youngest Olympic medallist. No motor, still very fast.', SRC.maxMaeder),
      q('yip-pin-xiu-backstroke', 'Yip Pin Xiu, Singapore’s first Paralympic gold medallist, is best known for which stroke?', ['Breaststroke', 'Backstroke', 'Butterfly', 'Dog paddle'], 1, 'Yip won Singapore’s first Paralympic gold in the 50m backstroke S3 at Beijing 2008.', SRC.yipPinXiu),
      q('shanti-pereira-asian-games', 'Shanti Pereira became Singapore’s first Asian Games athletics champion in 49 years by winning which event?', ['100m hurdles', '400m', 'Long jump', '200m'], 3, 'Pereira won the women’s 200m at Hangzhou 2022, staged in 2023. She also took 100m silver.', SRC.shantiPereira),
      q('loh-kean-yew-world-title', 'Loh Kean Yew became Singapore’s first world champion in which sport in 2021?', ['Table tennis', 'Badminton', 'Squash', 'Tennis'], 1, 'Loh won the men’s singles title at the 2021 BWF World Championships. Shuttlecock: defeated.', SRC.lohKeanYew),
      q('beijing-table-tennis-silver', 'Which sport ended Singapore’s 48-year Olympic medal wait at Beijing 2008?', ['Table tennis', 'Sailing', 'Shooting', 'Bowling'], 0, 'Li Jiawei, Feng Tianwei and Wang Yuegu won women’s team silver in table tennis.', SRC.tableTennisOlympics),
      q('laurentia-tan-dressage', 'Laurentia Tan won Singapore’s first Paralympic medal in which sport?', ['Wheelchair racing', 'Boccia', 'Para-equestrian dressage', 'Goalball'], 2, 'Tan and her horse Nothing to Lose won two dressage bronzes at Beijing 2008. Excellent horse name; even better result.', SRC.laurentiaTan),
      q('nur-syahidah-world-archery', 'Nur Syahidah Alim became Singapore’s first world champion archer in which event?', ['Compound women’s open', 'Recurve mixed team', 'Longbow', 'Crossbow sprint'], 0, 'She won the compound women’s open at the 2019 World Archery Para Championships.', SRC.nurSyahidah),
      q('fandi-fc-groningen', 'Football legend Fandi Ahmad scored against Inter Milan while playing for which European club?', ['Ajax', 'Celtic', 'FC Groningen', 'Barcelona'], 2, 'Fandi scored for Dutch club FC Groningen in a 2–0 UEFA Cup win over Inter Milan in 1983.', SRC.fandiAhmad),
      q('ang-peng-siong-event', 'Ang Peng Siong was named the world’s fastest swimmer in 1982 after excelling in which event?', ['50m freestyle', '200m backstroke', '100m breaststroke', '1500m freestyle'], 0, 'His 22.69-second 50m freestyle made him the world’s fastest over the distance that year.', SRC.angPengSiong),
      q('remy-ong-busan-2002', 'How many bowling gold medals did Remy Ong win at the 2002 Asian Games?', ['One', 'Two', 'Three', 'Five'], 2, 'Ong won three: singles, trios and masters. One trip, quite a lot of excess baggage.', SRC.remyOng),
      q('sheik-farhan-silat', 'Sheik Farhan won multiple world titles representing Singapore in which martial art?', ['Judo', 'Pencak silat', 'Taekwondo', 'Kendo'], 1, 'Farhan became a senior world champion in pencak silat, following a family steeped in the sport.', SRC.sheikFarhan),
      q('lau-ywen-fencing', 'Lau Ywen earned Singapore’s first Cadet and Junior World Championships gold in which sport?', ['Fencing', 'Archery', 'Gymnastics', 'Wushu'], 0, 'The sabre fencer delivered Singapore’s first gold at the championships in 2016.', SRC.lauYwen),
      q('water-polo-sea-games-streak', 'Which team sport won Singapore 27 straight SEA Games gold medals before the streak ended in 2019?', ['Basketball', 'Hockey', 'Volleyball', 'Men’s water polo'], 3, 'Singapore’s men were 27-time consecutive SEA Games champions entering the 2019 edition.', SRC.waterPolo),
      q('youth-olympics-2010', 'Singapore hosted the first-ever edition of which global multi-sport event in 2010?', ['World Beach Games', 'Youth Olympic Games', 'Invictus Games', 'Asian Indoor Games'], 1, 'The inaugural Summer Youth Olympic Games brought more than 3,500 young athletes to Singapore.', SRC.youthOlympics),
      q('world-aquatics-2025', 'Singapore became the first Southeast Asian host of which championships in 2025?', ['World Aquatics Championships', 'Winter Olympics', 'Rugby World Cup', 'Tour de France'], 0, 'Singapore 2025 was the first World Aquatics Championships staged in Southeast Asia.', SRC.worldAquatics),
      q('f1-night-race', 'What Formula 1 first did Singapore introduce in 2008?', ['First electric race', 'First night-time Grand Prix', 'First indoor circuit', 'First two-day race'], 1, 'The inaugural Marina Bay race was Formula 1’s first night-time Grand Prix. The floodlights also saw everything.', SRC.f1),
      q('kallang-roar', 'What was the legendary “Kallang Roar”?', ['A stadium crowd’s thunderous support', 'A racing-engine design', 'A dragon-boat command', 'A national dance move'], 0, 'The phrase captures the deafening support of fans at Singapore’s National Stadium in Kallang.', SRC.kallang),
      q('national-stadium-dome', 'Which record-setting feature crowns Singapore’s National Stadium?', ['Largest glass scoreboard', 'Tallest goalposts', 'Largest free-spanning dome', 'Longest running track'], 2, 'The 55,000-seat stadium is topped by the world’s largest free-spanning dome, spanning about 312 metres.', SRC.nationalStadium)
    ]
  },
  {
    title: 'Singapore on the world stage',
    description: 'Actors, filmmakers, musicians, writers and cultural exports. Yes, Batman is in this round.',
    category: CATEGORY.SCREEN_STAGE,
    questions: [
      q('chin-han-dark-knight', 'Which Singaporean actor played Lau in The Dark Knight?', ['Pierre Png', 'Chin Han', 'Adrian Pang', 'Hossan Leong'], 1, 'Ng Chin Han played Gotham businessman Lau in Christopher Nolan’s 2008 Batman film.', SRC.chinHan),
      q('fann-wong-shanghai-knights', 'Fann Wong made her Hollywood debut in which Jackie Chan sequel?', ['Rush Hour 2', 'The Tuxedo', 'Around the World in 80 Days', 'Shanghai Knights'], 3, 'Fann Wong played Chon Lin in the 2003 action-comedy Shanghai Knights.', SRC.fannWong),
      q('pierre-png-crazy-rich-asians', 'Who played Michael Teo, Astrid’s husband, in Crazy Rich Asians?', ['Pierre Png', 'Chin Han', 'Desmond Tan', 'Gurmit Singh'], 0, 'Singaporean actor Pierre Png made his Hollywood feature debut as Michael Teo.', SRC.pierrePng),
      q('ross-butler-13-reasons', 'Singapore-born Ross Butler played Zach Dempsey in which series?', ['Riverdale only', 'The Good Place', '13 Reasons Why', 'Never Have I Ever'], 2, 'Ross Butler is known for playing Zach Dempsey in 13 Reasons Why and was born in Singapore.', SRC.rossButler),
      q('anthony-chen-ilo-ilo', 'Which Anthony Chen film won the Caméra d’Or at Cannes in 2013?', ['Wet Season', 'Ilo Ilo', 'A Land Imagined', 'Apprentice'], 1, 'Ilo Ilo won Cannes’ award for best first feature, a landmark for Singapore cinema.', SRC.iloIlo),
      q('sandi-tan-shirkers', 'Sandi Tan won a Sundance directing award for which documentary?', ['Shirkers', 'Singapore Dreaming', 'I Not Stupid', 'Mee Pok Man'], 0, 'Shirkers won the 2018 Sundance Directing Award for World Cinema Documentary.', SRC.shirkers),
      q('kirsten-tan-pop-aye', 'What animal drives the road trip in Kirsten Tan’s award-winning Pop Aye?', ['Tiger', 'Horse', 'Elephant', 'Crocodile'], 2, 'Pop Aye follows a man taking his long-lost elephant home and won a Sundance screenwriting prize.', SRC.popAye),
      q('eric-khoo-12-storeys', 'Which Eric Khoo film became the first Singapore film in Cannes’ official selection?', ['Be with Me', 'Mee Pok Man', 'My Magic', '12 Storeys'], 3, '12 Storeys was selected for Cannes’ Un Certain Regard section in 1997.', SRC.ericKhoo),
      q('boo-junfeng-apprentice', 'Which Boo Junfeng film premiered in Cannes’ Un Certain Regard section in 2016?', ['Apprentice', 'Sandcastle', 'A Yellow Bird', 'Ilo Ilo'], 0, 'Apprentice, a drama centred on a prison executioner, premiered in Un Certain Regard.', SRC.booJunfeng),
      q('sonny-liew-eisners', 'How many Eisner Awards did Sonny Liew’s The Art of Charlie Chan Hock Chye win in 2017?', ['One', 'Three', 'Five', 'Seven'], 1, 'It won three: Best Writer/Artist, Best Publication Design and Best U.S. Edition of International Material—Asia.', SRC.sonnyLiew, CATEGORY.ARTS),
      q('dick-lee-home', 'Who wrote and composed the National Day song “Home”?', ['Jeremy Monteiro', 'Ken Lim', 'Dick Lee', 'JJ Lin'], 2, 'Dick Lee wrote “Home”, first used as the National Day Parade theme song in 1998.', SRC.nationalSongs, CATEGORY.ARTS),
      q('stefanie-sun-yanzi', 'Which Singaporean Mandopop star is also known as Sun Yanzi?', ['Stefanie Sun', 'Tanya Chua', 'Kit Chan', 'Olivia Ong'], 0, 'Stefanie Sun became a major Mandopop star after her 2000 debut and is widely known as Sun Yanzi.', SRC.stefanieSun, CATEGORY.ARTS),
      q('taufik-singapore-idol', 'Who won the first Singapore Idol in 2004?', ['Hady Mirza', 'Sylvester Sim', 'Sezairi Sezali', 'Taufik Batisah'], 3, 'Taufik Batisah won the inaugural Singapore Idol and built a regional music career from there.', SRC.taufik, CATEGORY.ARTS),
      q('tanya-golden-melody', 'Which singer became the first person to win Taiwan’s Best Mandarin Female Singer award four times?', ['Stefanie Sun', 'Tanya Chua', 'Kit Chan', 'Corrinne May'], 1, 'Singaporean singer-songwriter Tanya Chua achieved the four-win Golden Melody record.', SRC.tanya, CATEGORY.ARTS),
      q('shabir-vasantham-star', 'Which artist won the inaugural Vasantham Star in 2005?', ['Shabir Sulthan', 'Taufik Batisah', 'Hady Mirza', 'Nathan Hartono'], 0, 'Shabir Sulthan won the first Vasantham Star and later became an international Tamil composer and performer.', SRC.shabir, CATEGORY.ARTS),
      q('amanda-ministry-moral-panic', 'Amanda Lee Koe became the youngest Singapore Literature Prize winner with which collection?', ['Ponti', 'State of Emergency', 'Ministry of Moral Panic', 'The Gatekeeper'], 2, 'Her short-story collection Ministry of Moral Panic won the prize in 2014.', SRC.amanda, CATEGORY.ARTS),
      q('haresh-off-centre', 'Which playwright wrote the landmark Singapore play Off Centre?', ['Alfian Sa’at', 'Haresh Sharma', 'Michael Chiang', 'Ovidia Yu'], 1, 'Haresh Sharma, resident playwright of The Necessary Stage, wrote Off Centre.', SRC.haresh),
      q('ivan-wild-rice', 'Ivan Heng founded which Singapore theatre company?', ['The Necessary Stage', 'TheatreWorks', 'Singapore Repertory Theatre', 'Wild Rice'], 3, 'Ivan Heng founded Wild Rice in 2000 and serves as its founding artistic director.', SRC.ivan),
      q('jj-lin-music-voyager', 'What was JJ Lin’s 2003 debut album?', ['Music Voyager', 'Cao Cao', 'Stories Untold', 'Message in a Bottle'], 0, 'Singaporean Mandopop singer JJ Lin debuted with Music Voyager in 2003.', SRC.jjLin, CATEGORY.ARTS),
      q('phua-chu-kang-yellow-boots', 'Which Singapore TV character was a contractor with permed hair and trademark yellow boots?', ['Tan Ah Teck', 'Phua Chu Kang', 'Under One Roof’s Paul', 'VR Man'], 1, 'Gurmit Singh’s Singlish-speaking Phua Chu Kang starred in Singapore’s longest-running English-language sitcom. Don’t play-play.', SRC.phuaChuKang)
    ]
  },
  {
    title: 'Made here & Down Under',
    description: 'Singapore originals meet surprising Australia links. Canberra is closer than the departure board suggests.',
    category: CATEGORY.INNOVATION,
    questions: [
      q('sound-blaster', 'Which Singapore-made product became a global PC-audio standard after its 1989 launch?', ['PalmPilot', 'Walkman', 'Sound Blaster', 'Game Boy'], 2, 'Creative Technology launched the Sound Blaster card at COMDEX in Las Vegas in 1989.', SRC.soundBlaster),
      q('thumbdrive', 'Which Singapore company introduced the ThumbDrive USB storage device?', ['Trek 2000', 'Creative Technology', 'Razer', 'Sea Group'], 0, 'Singapore company Trek 2000 created and launched the thumb-sized USB storage product.', SRC.thumbDrive),
      q('newater', 'Where did NEWater make its big public debut in 2002?', ['At the Singapore Grand Prix', 'At National Day Parade', 'At Changi Terminal 4', 'At the Night Safari'], 1, 'At the 2002 National Day Parade, 60,000 people toasted the nation with bottled NEWater.', SRC.newater),
      q('erp', 'Singapore’s Electronic Road Pricing system is designed mainly to manage…', ['Rainfall', 'Airport queues', 'Housing prices', 'Road congestion'], 3, 'ERP was introduced in 1998 to manage traffic congestion through road pricing.', SRC.erp),
      q('singapore-sling', 'Who is credited with creating the Singapore Sling at Raffles Hotel?', ['Ngiam Tong Boon', 'Tan Tock Seng', 'Lim Bo Seng', 'William Farquhar'], 0, 'Raffles bartender Ngiam Tong Boon is credited with perfecting the pink gin cocktail around 1915.', SRC.sling),
      q('night-safari', 'What world-first claim belongs to Singapore’s Night Safari?', ['First zoo in an airport', 'First underwater zoo', 'First nocturnal wildlife park', 'First zoo without mammals'], 2, 'Opened in 1994, Night Safari is recognised as the world’s first nocturnal wildlife park.', SRC.nightSafari),
      q('australia-csp-2015', 'Singapore and Australia established their Comprehensive Strategic Partnership in which year?', ['2005', '2010', '2015', '2020'], 2, 'The two countries established the partnership in 2015, their 50th year of diplomatic relations.', SRC.australiaCsp, CATEGORY.AUSTRALIA),
      q('airport-butterfly-garden', 'Which world-first can travellers find inside Changi Airport?', ['Airport butterfly garden', 'Airport ski slope', 'Airport coral reef', 'Airport vineyard'], 0, 'Terminal 3 houses the world’s first butterfly garden in an airport, with more than 1,000 butterflies.', SRC.butterfly),
      q('sky-greens', 'Singapore’s Sky Greens pioneered a low-carbon vertical farm driven by what?', ['Coal-fired belts', 'Jet engines', 'Geothermal steam', 'Hydraulic water-pulley systems'], 3, 'Its vertical growing towers rotate using a low-energy hydraulic water-pulley system.', SRC.skyGreens),
      q('rain-vortex', 'How tall is Jewel Changi’s world-record indoor Rain Vortex?', ['20 metres', '30 metres', '40 metres', '60 metres'], 2, 'The Rain Vortex falls 40 metres through Jewel—seven storeys of extremely committed water.', SRC.rainVortex),
      q('australia-recognition', 'Australia was which country to recognise independent Singapore in 1965?', ['First', 'Second', 'Fifth', 'Tenth'], 1, 'Australia was the second country to recognise Singapore after independence.', SRC.australiaBrief, CATEGORY.HISTORY),
      q('safta', 'The Singapore–Australia Free Trade Agreement was originally signed in…', ['2003', '1991', '2015', '2022'], 0, 'SAFTA was originally signed in 2003 and has since been updated several times.', SRC.australiaBrief, CATEGORY.AUSTRALIA),
      q('digital-economy-agreement', 'Australia was Singapore’s first bilateral partner for what kind of agreement?', ['Space-launch agreement', 'Fisheries-only pact', 'Digital Economy Agreement', 'Common currency treaty'], 2, 'The Singapore–Australia Digital Economy Agreement entered into force in December 2020.', SRC.digitalAgreement, CATEGORY.AUSTRALIA),
      q('green-economy-agreement', 'The 2022 Singapore–Australia Green Economy Agreement combines climate goals with…', ['Military conscription', 'Sporting rules', 'Immigration quotas', 'Trade and economic cooperation'], 3, 'The first-of-its-kind agreement links climate, trade and economic objectives.', SRC.greenAgreement, CATEGORY.AUSTRALIA),
      q('exercise-wallaby', 'Exercise Wallaby has brought Singapore Armed Forces personnel to train in which Australian state since 1990?', ['Queensland', 'Tasmania', 'Victoria', 'Western Australia'], 0, 'Exercise Wallaby began at Shoalwater Bay Training Area in Queensland in 1990.', SRC.wallaby, CATEGORY.AUSTRALIA),
      q('fpda', 'Australia and Singapore belong to the FPDA with which other three countries?', ['India, Japan and Indonesia', 'Malaysia, New Zealand and the UK', 'France, Thailand and Brunei', 'Canada, Fiji and the US'], 1, 'The Five Power Defence Arrangements unite Australia, Malaysia, New Zealand, Singapore and the United Kingdom.', SRC.fpda, CATEGORY.AUSTRALIA),
      q('canberra-mrt', 'Which Singapore MRT station shares its name with Australia’s capital?', ['Darwin', 'Sydney', 'Canberra', 'Hobart'], 2, 'Canberra MRT takes its name from nearby Canberra Link, itself named after Australia’s capital.', SRC.canberra, CATEGORY.AUSTRALIA),
      q('christmas-island', 'In 1958, which territory was transferred from colonial Singapore to Australia?', ['Norfolk Island', 'Cocos Island', 'Sentosa', 'Christmas Island'], 3, 'Sovereignty over Christmas Island was transferred to Australia on 1 October 1958.', SRC.christmasIsland, CATEGORY.HISTORY),
      q('changi-australian-pows', 'After Singapore fell in 1942, where were many captured Australian troops first held?', ['Changi', 'Pulau Ubin', 'Fort Canning', 'Jurong Island'], 0, 'Many members of Australia’s 8th Division were held at Changi before some were sent to forced-labour sites elsewhere.', SRC.changiPow, CATEGORY.HISTORY),
      q('australia-sea-trade-partner', 'Within Southeast Asia, Singapore is Australia’s largest partner for which combined measure?', ['Tourist visas only', 'Two-way trade and investment', 'Wheat production', 'Film co-productions only'], 1, 'Australia’s government identifies Singapore as its largest Southeast Asian partner for two-way trade and investment.', SRC.australiaBrief, CATEGORY.AUSTRALIA)
    ]
  }
];

rounds.forEach(round => {
  round.questions.forEach(question => {
    question.category ||= round.category;
  });
});

if (rounds.some(round => round.questions.length !== 20)) {
  throw new Error('Every theme must contain exactly 20 questions.');
}
